### PR TITLE
Fixcss

### PR DESCRIPTION
**Pull request by caseycesari**
Still working on this. First step was to pull out CSS from JS file and move it into an external file. Next step is to implement some resets and healthy cross browser defaults to address #40 and discussion in #42.

### CODE REVIEW

**Comment by palewire** [comment]
Looks like a good start. Should we hold off on the merge?

**Comment by caseycesari** [comment]
Yeah. I'll continue to work on this branch.

**Comment by palewire** [comment]
I think I got this all done now in version 0.2.0. Check it out.

**Comment by caseycesari** [comment]
Cool! Sorry I didn't get around to finishing this up. 0.2.0 is looking good. I'll give it a whirl soon.

**Pull request closed without merging**
