### PR TITLE
If available the input placeholder attribute is a nicer experience

### PR DESCRIPTION
**Pull request by albertsun**
detecting HTML5 input placeholder attribute and using that for initialText if supported.

another separate commit to add a regionBiasFilter option to filter to just the country specified in regionBias. (guess I could separate these, didn't think they'd go to the same pull request)

### CODE REVIEW

**Comment by albertsun** [comment]
So... Modernizr is a js library that does faeture detection for new new JS/HTML5/CSS3 features and provides a global object you can check to see if a specific feature is supported. http://www.modernizr.com/docs/#features-html5

For example, to see if the new "placeholder" attribute of an HTML5 input element will work or not, like it does in modern browsers. In new browsers, setting that to initialText will clear the field on focus, and restore the placeholder text if the field goes unfocused while empty.

What I'm doing at the top is checking to see if a proper version of Modernizr is available, and if not then doing the same test that it would do to check if placeholder is supported.

If it is supported, then you don't need to bind the focus event.

**Comment by palewire** [comment]
Thanks for the schooling. Do you know of any other jQuery libraries that integrate Modernizr like this?

**Comment by albertsun** [comment]
I don't know of any others that integrate Modernizr like this. Could just do the check with these two lines

```
var i = document.createElement('input');
return 'placeholder' in i;
```

and store the value somewhere else instead of bothering with the Modernizr checks.

**Comment by albertsun** [comment]
ok, these have kind of diverged. i'm going to close this.

**Comment by palewire** [comment]
Alright. Let's try to get modernizr in there, tho. I've been out of town and a bit lazy.

**Pull request closed without merging**
